### ISSUE TITLE
Add some graphql quickstart guides to miragejs.com

### ISSUE THREAD

**Issue by samselikoff** [miragejs/graphql-examples#1]
Would love to get a GraphQL section added under [the Quickstarts section of miragejs.com](https://miragejs.com/quickstarts/react/development)!

The site's repo is here: https://github.com/miragejs/site

**Comment by viperfx** [comment]
@samselikoff the graphql example is really great. It would be great to have an example on how mutations could work.

Have you done anything offline on it?

**Comment by samselikoff** [comment]
@viperfx no but the resolver code would look similar - it would use the data from the payload and interact with `schema`.

I'd watch [this issue](https://github.com/miragejs/site/issues/264) because we are going to be adding a full graphql example on the site soon!

**Comment by samselikoff** [comment]
Closing in favor of https://github.com/miragejs/site/issues/264
